[package]
name = "fuzzy_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "fuzzy_rust"
crate-type = ["cdylib"]

[dependencies]
fuzzy-matcher = "0.3.7"
pyo3 = "0.25.0"
rayon = "1.10.0"
